# Generated by Django 5.0.7 on 2024-10-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning_path", "0003_chapter_chapter_num"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(),
        ),
    ]
