# Generated by Django 5.0.7 on 2024-10-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning_path", "0004_alter_course_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chapter",
            name="description",
            field=models.TextField(),
        ),
    ]
