# Generated by Django 5.0.7 on 2024-09-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BlogPost", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PostImages",
            new_name="PostImage",
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(),
        ),
    ]
