# Generated by Django 5.0.7 on 2024-09-24 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPost', '0002_rename_postimages_postimage_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', '0'), ('Published', '1')], max_length=10, null=True),
        ),
    ]
