# Generated by Django 5.0.7 on 2024-09-24 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPost', '0003_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(blank=True, choices=[('0', 'Pending'), ('1', 'Published')], max_length=10, null=True),
        ),
    ]
