# Generated by Django 5.0.7 on 2024-09-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPost', '0004_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('0', 'Pending'), ('1', 'Published')], default='0', max_length=10, null=True),
        ),
    ]
