# Generated by Django 5.0.7 on 2024-09-25 06:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BlogPost", "0005_alter_post_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="likes",
            field=models.ManyToManyField(
                null=True, related_name="post_likes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
