# Generated by Django 5.0.7 on 2024-10-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BlogPost", "0007_alter_post_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="description",
            field=models.TextField(),
        ),
    ]
