# Generated by Django 5.0.7 on 2025-02-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPost', '0008_alter_post_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_type',
            field=models.CharField(choices=[('0', 'Markdown'), ('1', 'IPYNB')], default='0', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='ipynb',
            field=models.FileField(blank=True, null=True, upload_to='notebooks/'),
        ),
    ]
