# Generated by Django 5.0.7 on 2024-08-28 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContestProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('problem_link', models.URLField(default='')),
                ('successful_submissions', models.IntegerField()),
                ('accuracy', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('contest', models.CharField(max_length=50)),
                ('link', models.URLField()),
                ('solution_link', models.URLField(default='')),
                ('date', models.DateField()),
                ('duration', models.SmallIntegerField()),
                ('contest_problems', models.ManyToManyField(to='upsolve.contestproblem')),
            ],
        ),
    ]
