# Generated by Django 5.0.7 on 2024-09-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upsolve", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="contestproblem",
            name="accuracy",
        ),
        migrations.RemoveField(
            model_name="contestproblem",
            name="successful_submissions",
        ),
        migrations.AddField(
            model_name="contestproblem",
            name="rating",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contestproblem",
            name="problem_tags",
            field=models.ManyToManyField(to="upsolve.tag"),
        ),
    ]
