# Generated by Django 5.0.7 on 2024-09-13 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upsolve", "0002_tag_remove_contestproblem_accuracy_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contestproblem",
            name="submissions",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
