# Generated by Django 5.0.7 on 2024-10-03 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("upsolve", "0003_contestproblem_submissions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contestproblem",
            name="submissions",
        ),
    ]
