# Generated by Django 5.0.7 on 2024-10-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upsolve", "0004_remove_contestproblem_submissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contestproblem",
            name="problem_tags",
            field=models.ManyToManyField(related_name="tags", to="upsolve.tag"),
        ),
    ]
