# Generated by Django 5.0.7 on 2024-10-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upsolve", "0006_remove_contest_contest_problems_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contestproblem",
            name="contest",
        ),
        migrations.AddField(
            model_name="contest",
            name="contest_problems",
            field=models.ManyToManyField(to="upsolve.contestproblem"),
        ),
    ]
