# Generated by Django 5.0.7 on 2024-10-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upsolve", "0008_problem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contest",
            name="contest_problems",
        ),
        migrations.AddField(
            model_name="problem",
            name="code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="problem",
            name="problem_tags",
            field=models.ManyToManyField(related_name="tags", to="upsolve.tag"),
        ),
        migrations.DeleteModel(
            name="ContestProblem",
        ),
    ]
