# Generated by Django 5.0.7 on 2024-07-30 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_student_codechef_id_alter_student_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Codechef_database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_contest', models.CharField(blank=True, max_length=10, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('plagarisms', models.IntegerField(blank=True, null=True)),
                ('stars', models.IntegerField(blank=True, null=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.student')),
            ],
        ),
    ]
