# Generated by Django 5.0.7 on 2024-07-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_codechef_database'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codechef_database',
            old_name='rating',
            new_name='latest_rank',
        ),
        migrations.AddField(
            model_name='codechef_database',
            name='latest_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='codechef_database',
            name='no_of_contests',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='codechef_database',
            name='no_of_problems',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
