# Generated by Django 5.0.7 on 2024-07-31 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_rename_rating_codechef_database_latest_rank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codechef_database',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.student'),
        ),
    ]
