# Generated by Django 5.0.1 on 2024-08-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_codechef_database_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='codechef_database',
            name='contest_problems',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
