# Generated by Django 5.0.7 on 2024-09-14 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_codechef_database_contest_problems'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_name', models.CharField(max_length=100)),
                ('contest_code', models.CharField(max_length=10)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('problems_solved', models.IntegerField(blank=True, null=True)),
                ('contests_participated', models.IntegerField(blank=True, null=True)),
                ('plagarisms', models.IntegerField(blank=True, null=True)),
                ('stars', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.student')),
            ],
        ),
    ]
