# Generated by Django 5.0.7 on 2024-09-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_contestperformance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestperformance',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
