# Generated by Django 5.0.7 on 2024-07-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_sections_student_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='codechef_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
