# Generated by Django 5.0.7 on 2024-09-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discuss", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
