# Generated by Django 5.0.7 on 2024-10-01 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discuss", "0003_alter_comment_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.CharField(max_length=1000),
        ),
    ]
