# Generated by Django 5.0.7 on 2024-10-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discuss", "0004_alter_comment_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.TextField(),
        ),
    ]
