# Generated by Django 5.0.7 on 2024-10-03 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discuss", "0005_alter_comment_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discussion",
            name="content",
            field=models.TextField(),
        ),
    ]
