# Generated by Django 5.0.7 on 2024-08-17 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=200)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('edited_on', models.DateField(auto_now_add=True)),
                ('description', models.CharField(max_length=200)),
                ('post', models.TextField()),
                ('banner', models.ImageField(blank=True, null=True, upload_to='resources/media/')),
                ('pictures', models.ImageField(blank=True, null=True, upload_to='resources/media/')),
                ('author', models.CharField(max_length=100)),
            ],
        ),
    ]
