# Generated by Django 5.0.7 on 2024-08-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='edited_on',
            field=models.DateField(),
        ),
    ]
