# Generated by Django 5.0.7 on 2024-08-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_alter_post_created_on_alter_post_edited_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pictures',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/'),
        ),
    ]
