# Generated by Django 5.0.7 on 2024-08-22 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_posttag_post_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tag',
            new_name='tags',
        ),
        migrations.AlterField(
            model_name='posttag',
            name='post_tag',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
