# Generated by Django 5.0.7 on 2024-08-22 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_rename_tag_post_tags_alter_posttag_post_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=200)),
                ('link', models.URLField(default='')),
                ('parent_post', models.ManyToManyField(to='resources.post')),
            ],
        ),
    ]
