# Generated by Django 5.0.7 on 2024-09-17 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0006_subpost"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SubPost",
        ),
    ]
