# Generated by Django 5.0.7 on 2024-09-15 14:18

import markdownfield.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "content",
                    markdownfield.models.MarkdownField(rendered_field="text_rendered"),
                ),
                ("text_rendered", markdownfield.models.RenderedMarkdownField()),
                ("created_at", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
