# Generated by Django 5.0.7 on 2024-09-15 15:14

import markdownfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog_test", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpage",
            name="content",
            field=markdownfield.models.MarkdownField(),
        ),
    ]
