# Generated by Django 5.0.7 on 2024-09-15 15:30

import markdownfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog_test", "0002_alter_blogpage_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpage",
            name="content",
            field=markdownfield.models.MarkdownField(rendered_field="text_rendered"),
        ),
    ]
