# Generated by Django 5.0.7 on 2024-09-16 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog_test", "0003_alter_blogpage_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpage",
            name="content",
        ),
        migrations.RemoveField(
            model_name="blogpage",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="blogpage",
            name="text_rendered",
        ),
    ]
